### ISSUE TITLE
Vue Equipment stops working after updating Nuxt to 4.5.1 (Security Release)

### ISSUE THREAD

**Issue by plcdnl** [magicasaservice/vue-equipment#429]
### Description of the bug

After updating Nuxt to version 4.5.1 (Security Release), the build/server startup fails with the following error:
```
Cannot find module '/<path>/node_modules/.pnpm/@maas+vue-equipment@1.0.0-beta.79_b194f927dc1c93ef9999d156aea32299/node_modules/@maas/vue-equipment/dist/plugins/MagicError/dist/index.js' imported from '/<path>/node_modules/.pnpm/@maas+vue-equipment@1.0.0-beta.79_b194f927dc1c93ef9999d156aea32299/node_modules/@maas/vue-equipment/dist/plugins/MagicDrawer/src/components/MagicDrawerTrigger.vue'
```

### Steps To Reproduce

Environment:
```
@maas/vue-equipment: 1.0.0-beta.79
nuxt: 4.5.1
Package manager: pnpm
```

1. Update Nuxt to version 4.5.1
2. Build or run the server (build/dev)
3. The process fails with the Cannot find module error shown above

**Comment by robinscholz** [comment]
cheers, that package.json was indeed not supposed to be there at all. I just published a fix!
